# DEPRECATED! DO NOT USE OR REMOVE THIS! THESE ARE JUST HERE TO PRESERVE
# LAUNCHING THIS OLDER VERSION.

name: ðŸš€ 4.0.0-alpha.2

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: libhal/ci/.github/workflows/deploy_all.yml@5.x.y
    with:
      version: 4.0.0-alpha.2
    secrets: inherit
